### ISSUE TITLE
why /var/log/tinyproxy/tinyproxy.log is empty

### ISSUE THREAD

**Issue by tfchen2400** [monokal/docker-tinyproxy#11]
i user the cmd docker run -d --name='tinyproxy' -p 8888:8888 dannydirect/tinyproxy:latest ANY

request http with proxy 

import requests

proxy_dict = {
    "http": "http://192.168.80.77:8888/"
}

a = requests.get(url='http://www.baidu.com', proxies=proxy_dict)

print(a.content.decode("utf-8"))

but the log is empty why?

docker logs has some logs,but not satisfy to me.

i want the request log

**Comment by monokal** [comment]
Logs are piped to STDOUT, as is usually the case in Docker.
