### ISSUE TITLE
wrong path

### ISSUE THREAD

**Issue by johnqube** [monokal/docker-tinyproxy#16]
hello when running image from `docker pull dannydirect/tinyproxy`

error throws :

`/opt/docker-tinyproxy/run.sh: line 150: /usr/bin/tinyproxy: No such file or directory`

tinyproxy executable seems to be in /usr/sbin

I suggest to fix this in the run.sh

**Comment by monokal** [comment]
Use monokal/tinyproxy

**Comment by aogg** [comment]
+1
