### ISSUE TITLE
PROXY_CONF='/etc/tinyproxy/tinyproxy.conf'

### ISSUE THREAD

**Issue by morriswinkler-simple** [monokal/docker-tinyproxy#2]
PROXY_CONF='/etc/tinyproxy/tinyproxy.conf'

i checked the image it uses '/etc/tinyproxy.conf'

there is no file /etc/tinyproxy/tinyproxy.conf

**Comment by monokal** [comment]
Amended run.sh

**Comment by dkam** [comment]
But now you can't provide your own tinyproxy.conf with -v /etc/tinyproxy:/etc/tinyproxy?  I'm new to Docker, maybe I'm missing something?

**Comment by monokal** [comment]
I don't see why this would prevent that @dkam, this was only a change to the default location of tinyproxy.conf, which you should still be able to mount. Are you having issues?
