### ISSUE TITLE
TinyProxy Release v1.10.0

### ISSUE THREAD

**Issue by mt-kelvintaywl** [monokal/docker-tinyproxy#9]
It seems that TinyProxy recently released 1.10.0.
> https://github.com/tinyproxy/tinyproxy/releases/tag/1.10.0

As of the current Docker image here, i checked that it is still on 1.8.4.

I was wondering if we can update the docker image once more so it should pick up the latest tinyproxy for installation?

**Comment by mt-kelvintaywl** [comment]
```sh
# assuming a docker container `my_tinyproxy`
$ docker exec -it my_tinyproxy tinyproxy -v

tinyproxy 1.8.4
```

**Comment by mt-kelvintaywl** [comment]
@monokal sorry to ping you, but i was testing this with a local build of this dockerfile:

and verified that with the updated tinyproxy (v1.10.0), we get stdout logging for free :)

**Comment by monokal** [comment]
Hi @mt-kelvintaywl, feel free to open a PR and I'll be more than happy to merge.
